export const products = [
  // Dog Products
  {
    id: 1,
    name: "Premium Dog Leash",
    price: 24.99,
    image: "/images/images.jpg",
    collections: "dog",
  },
  {
    id: 2,
    name: "Dog Food Bowl",
    price: 19.99,
    image: "/images/DogBowl.jpg",
    collections: "dog",
  },
  {
    id: 3,
    name: "Dog Chew Toy",
    price: 15.99,
    image: "/images/ChewToy.jpg",
    collections: "dog",
  },
  {
    id: 4,
    name: "Dog Brush",
    price: 12.99,
    image: "/images/DogBrush.jpg",
    collections: "dog",
  },
  {
    id: 5,
    name: "Dog Food 8kg",
    price: 29.99,
    image: "/images/DogFood.avif",
    collections: "dog",
  },
  {
    id: 6,
    name: "Dog Bed",
    price: 49.99,
    image: "/images/DogBed.jpg",
    collections: "dog",
  },
  {
    id: 7,
    name: "Dog Shampoo",
    price: 14.99,
    image: "/images/DogShampoo.jpg",
    collections: "dog",
  },
  {
    id: 8,
    name: "Dog Treats",
    price: 9.99,
    image: "/images/DogTreats.jpg",
    collections: "dog",
  },
  {
    id: 9,
    name: "Dog Ball",
    price: 7.99,
    image: "/images/DogBall.webp",
    collections: "dog",
  },
  {
    id: 10,
    name: "Dog Collar",
    price: 19.99,
    image: "/images/DogCollar.jpg",
    collections: "dog",
  },
  {
    id: 11,
    name: "Dog Harness",
    price: 29.99,
    image: "/images/DogHarness.jpg",
    collections: "dog",
  },
  {
    id: 12,
    name: "Puppy Pads",
    price: 24.99,
    image: "/images/PuppyPads.jpg",
    collections: "dog",
  },
  {
    id: 13,
    name: "Dog Dental Chews",
    price: 15.99,
    image: "/images/DentalChews.jpg",
    collections: "dog",
  },
  {
    id: 14,
    name: "Dog Water Bottle",
    price: 12.99,
    image: "/images/WaterBottle.jpg",
    collections: "dog",
  },
  {
    id: 15,
    name: "Dog Nail Clippers",
    price: 9.99,
    image: "/images/NailClippers.jpg",
    collections: "dog",
  },
  {
    id: 16,
    name: "Dog Flea Treatment",
    price: 34.99,
    image: "/images/FleaTreatment.jpg",
    collections: "dog",
  },
  {
    id: 17,
    name: "Dog Carrier",
    price: 45.99,
    image: "/images/DogCarrier.webp",
    collections: "dog",
  },
  {
    id: 18,
    name: "Training Treats",
    price: 8.99,
    image: "/images/TrainingTreats.jpg",
    collections: "dog",
  },
  {
    id: 19,
    name: "Dog Poop Bags",
    price: 6.99,
    image: "/images/PoopBags.jpg",
    collections: "dog",
  },
  {
    id: 20,
    name: "Dog Puzzle Toy",
    price: 19.99,
    image: "/images/PuzzleToy.jpg",
    collections: "dog",
  },
  {
    id: 21,
    name: "Dog Cooling Mat",
    price: 24.99,
    image: "/images/CoolingMat.jpg",
    collections: "dog",
  },
  {
    id: 22,
    name: "Dog Raincoat",
    price: 29.99,
    image: "/images/Raincoat.jpg",
    collections: "dog",
  },
  {
    id: 23,
    name: "Dog Frisbee",
    price: 11.99,
    image: "/images/Frisbee.webp",
    collections: "dog",
  },
  {
    id: 24,
    name: "Dog Tennis Balls",
    price: 7.99,
    image: "/images/TennisBalls.webp",
    collections: "dog",
  },
  {
    id: 25,
    name: "Dog Toothbrush Kit",
    price: 14.99,
    image: "/images/ToothbrushKit.jpg",
    collections: "dog",
  },

  // Cat Products
  {
    id: 26,
    name: "Cat Tower",
    price: 79.99,
    image: "/images/CatTower.jpg",
    collections: "cat",
  },
  {
    id: 27,
    name: "Cat Litter Box",
    price: 29.99,
    image: "/images/Litterbox.jpg",
    collections: "cat",
  },
  {
    id: 28,
    name: "Cat Food 2kg",
    price: 19.99,
    image: "/images/CatFood.webp",
    collections: "cat",
  },
  {
    id: 29,
    name: "Cat Brush",
    price: 11.99,
    image: "/images/CatBrush.jpg",
    collections: "cat",
  },
  {
    id: 30,
    name: "Cat Toys Set",
    price: 15.99,
    image: "/images/CatToys.jpg",
    collections: "cat",
  },
  {
    id: 31,
    name: "Cat Bed",
    price: 34.99,
    image: "../client/public/images/CatBed.jpg",
    collections: "cat",
  },
  {
    id: 32,
    name: "Cat Carrier",
    price: 39.99,
    image: "/images/CatCarrier.jpg",
    collections: "cat",
  },
  {
    id: 33,
    name: "Cat Scratching Post",
    price: 24.99,
    image: "/images/ScratchingPost.jpg",
    collections: "cat",
  },
  {
    id: 34,
    name: "Cat Water Fountain",
    price: 29.99,
    image: "/images/WaterFountain.jpg",
    collections: "cat",
  },
  {
    id: 35,
    name: "Cat Collar",
    price: 9.99,
    image: "/images/CatCollar.webp",
    collections: "cat",
  },
  {
    id: 36,
    name: "Cat Treats",
    price: 7.99,
    image: "/images/CatTreats.avif",
    collections: "cat",
  },
  {
    id: 37,
    name: "Cat Nail Clippers",
    price: 8.99,
    image: "/images/CatClippers.jpg",
    collections: "cat",
  },
  {
    id: 38,
    name: "Cat Flea Treatment",
    price: 32.99,
    image: "/images/CatFlea.webp",
    collections: "cat",
  },
  {
    id: 39,
    name: "Cat Laser Toy",
    price: 14.99,
    image: "/images/LaserToy.jpg",
    collections: "cat",
  },
  {
    id: 40,
    name: "Cat Litter",
    price: 19.99,
    image: "/images/CatLitter.jpg",
    collections: "cat",
  },
  {
    id: 41,
    name: "Cat Food Bowl",
    price: 12.99,
    image: "/images/CatBowl.jpg",
    collections: "cat",
  },
  {
    id: 42,
    name: "Catnip Toys",
    price: 9.99,
    image: "/images/CatnipToys.jpg",
    collections: "cat",
  },
  {
    id: 43,
    name: "Cat Grooming Glove",
    price: 11.99,
    image: "/images/GroomingGlove.jpg",
    collections: "cat",
  },
  {
    id: 44,
    name: "Cat Dental Treats",
    price: 8.99,
    image: "/images/DentalTreats.jpg",
    collections: "cat",
  },
  {
    id: 45,
    name: "Cat Window Perch",
    price: 27.99,
    image: "/images/WindowPerch.jpg",
    collections: "cat",
  },
  {
    id: 46,
    name: "Cat Climbing Shelf",
    price: 44.99,
    image: "/images/ClimbingShelf.avif",
    collections: "cat",
  },
  {
    id: 47,
    name: "Cat Travel Bag",
    price: 29.99,
    image: "/images/TravelBag.jpg",
    collections: "cat",
  },
  {
    id: 48,
    name: "Cat Wand Toy",
    price: 7.99,
    image: "/images/WandToy.jpg",
    collections: "cat",
  },
  {
    id: 49,
    name: "Cat Harness",
    price: 19.99,
    image: "/images/CatHarness.jpg",
    collections: "cat",
  },
  {
    id: 50,
    name: "Cat Cave Bed",
    price: 39.99,
    image: "/images/CaveBed.jpg",
    collections: "cat",
  },
];

export default products;
